### ISSUE TITLE
Add some sort of indicator if a file has both tabs AND spaces as indentation

### ISSUE THREAD

**Issue by scottchiefbaker** [tpope/vim-sleuth#13]
If a file has both spaces AND tabs as indentation it would be very handy if vim-slueth would pop up some sort of warning that indentation is inconsistent, so that I know I need to fix it.

**Comment by tpope** [comment]
Personally I wouldn't find this particularly helpful. For every one time I make this mistake myself, I have a hundred where I'm dealing with someone else's jank file, and I really don't want Sleuth twisting the knife with a nagging message. But the reason I'm going to say no is there just isn't a good way to deliver that message. Anything that interrupts the user with a "press ENTER" prompt sounds positively insufferable.
