### ISSUE TITLE
[Feature Request] Option to only go up N directories.

### ISSUE THREAD

**Issue by TheBlueMatt** [tpope/vim-sleuth#18]
I'd like to be able to set an option to only search up one or two directories (though best would be to only traverse up until you find a .git,.svn,etc). I know little of vim scripting, so I'm just gonna leave this here...

**Comment by sheerun** [comment]
https://github.com/sheerun/vim-polyglot plugin has an embedded, heavily modified version of vim-sleuth that goes up maximally 3 directories and stops if directory contains .git, .svn, .hg

**Comment by tpope** [comment]
With EditorConfig to fall back on for deeply nested projects, I'm open to trying out a limit of the containing directory and direct parent only.
