### ISSUE TITLE
Sleuth enables "filetype indent" unconditionally

### ISSUE THREAD

**Issue by dbarnett** [tpope/vim-sleuth#21]
If you have sleuth.vim installed, you will always have `filetype indent` enabled when plugin/sleuth.vim loads.

It may seem obvious that enabling an indentation-related plugin would enable extra indent settings on you, but since it loads after vimrc time and there's no `:verbose filetype` variant to troubleshoot what's overriding `:filetype` on you, it's pretty painful tracking down why you're not able to disable filetype indent from your vimrc if you decide to try it.

**Comment by sheerun** [comment]
vim-polyglot doesn't set filetype indent and it's up to user to set it (usually it's on by default)

**Comment by tpope** [comment]
My intent was that `let g:did_indent_on = 0` could be abused to opt out of this, but you make a good point about discoverability, so I'm adding a documented option.

> usually it's on by default

It's off by default on Debian based distros. That alone is a big enough exception that I think it's worth Sleuth taking responsibility for this.
