### ISSUE TITLE
vim-sleuth + vim-javascript = no indent at all

### ISSUE THREAD

**Issue by danielfalk** [tpope/vim-sleuth#25]
The notes for sleuth are quite clear: if a file is indented by tabs, then shiftwidth is set to 0.  This creates a problem when I want to use vim-javascript.  It seems that it wants to use the shiftwidth to indent, hence no indent at all.

So this is partly an issue, and partly a question.  Which is the correct behavior?  vim-javascript, or vim-sleuth?  I don't know myself, but looking here: http://vim.wikia.com/wiki/Indenting_source_code suggests that shiftwidth should be the same value as tabstop (see section "Indentation purely with hard tabs").

Incidentally, I have ts=4 and sw=4 in my vimrc, but sleuth overwrites this value for the js file I'm trying to edit.

Thank you for your attention.

**Comment by tpope** [comment]
This is a pretty severe unintended consequence of b6b4c3b237678f1214ea2eca0e3e50eaafb30e3a. I'll revert.

**Comment by axiom** [comment]
(I do believe this is due to `vim-javascript` using `&sw` instead of the recommended `shiftwidth()`.)

**Comment by tpope** [comment]
Yes, but `shiftwidth()` is brand new as of 7.4, while `'shiftwidth'` is as old as vi itself. The transition will take years.

**Comment by fd0** [comment]
For the record: https://github.com/fatih/vim-go had the same problem: https://github.com/fatih/vim-go/pull/308
