### ISSUE TITLE
Let me set default tab

### ISSUE THREAD

**Issue by channoh** [tpope/vim-sleuth#26]
Why don't you add some configurable variables for **heuristics.hard**? For example, something like below:

```vim
" at line 73 in sleuth.vim
if heuristics.hard
    let options.tabstop = sleuth_tabstop
endif
```

In addition, I think ```let options.shiftwidth = 8 ``` is missing at line 74.

Thanks!

**Comment by tpope** [comment]
This addresses the specific case of mixed tabs/spaces, which typically means tabs are used as a stand-in for 8 spaces.
