### ISSUE TITLE
Incorrect indentation in javascript files

### ISSUE THREAD

**Issue by rohanorton** [tpope/vim-sleuth#27]
I have a project I'm working on which contains javascript files indented with 4 spaces. When I try and use vim-sleuth with these it sets my indentation to 3 spaces.

The only file I can find that contains 3 space indent in the project is a LICENCE file in my root dir (where I usually launch vim from). Removing this file appears to result in my indentation being set to the desired 4 spaces. But since all my javascript files appear to be indented with 4 spaces, I would expect vim-sleuth to detect filetype and follow suit. Is this not the desired behaviour?

When I disable vim-sleuth my old default settings kick in and give me 4 space indentation, so I don't think it's another plugin affecting things.

**Comment by tpope** [comment]
That is weird. Does `:echo b:sleuth_culprit` return anything?

**Comment by rohanorton** [comment]
Oh, I no longer seem to able to reproduce it. Which is strange, as I'd been experiencing it over the past few days. Sorry to bother you. I'll try what you suggested if the issue reappears (currently that variable doesn't exist)
