### ISSUE TITLE
Support tabstop != 8

### ISSUE THREAD

**Issue by sasq64** [tpope/vim-sleuth#32]
The script seems to assume physical tabs are 8 spaces. Wouldn't it be better if it read the user set `tabstop` and used that value?

**Comment by tpope** [comment]
It does read it if you have a file with 100% tabs. It forces 8 on mixed files, because that's a popular historical practice.

**Comment by duganchen** [comment]
I need to be able to set mixed files to use tabstop=4 if I'm going to use this.

Would you be open to adding a config option for this?

**Comment by tpope** [comment]
Closing in favor of #17
