### ISSUE TITLE
tabstop defaults to 8 when 4 is set in vimrc

### ISSUE THREAD

**Issue by tsoernes** [tpope/vim-sleuth#41]
This is the file in question:
https://github.com/eLvErDe/museek-plus/blob/master/python-clients/museekcontrol
It seems consistently indented to me.
Setting tabstop to 4 after opening the file works just fine, but I have to do it every time as it seems that `set tabstop=4` in my vimrc is not working.

I don't have any other indent-settings in vimrc as far as I can tell. Here's the config: https://da.gd/GqXOa

**Comment by tpope** [comment]
Four lines begin with a single whitespace.

Side note: your GitHub link shows 8 space tabs too, might want to send a pull request to them as well. :upside_down_face:

**Comment by tsoernes** [comment]
I fixed those four lines beginning with space. Also fixed all lines beginning with tabs then space. Also fixed all occurrences of two or more consecutive spaces. Still, tabstop defaults to 8!
https://da.gd/vSwD8

**Comment by tpope** [comment]
https://github.com/vim/vim/blob/58556cd0e592cba75bf60310d822a20e41f6b02e/runtime/ftplugin/python.vim#L69-L72

**Comment by tsoernes** [comment]
Alright, that explains it.
I think Sleuth gets to do its work (at least tabstop is 4) if you set
```
let g:python_recommended_style = 0
```
I think that if you also add the line below, sleuth is ignored and PEP8 recommendations are enforced but with tabs displayed with a width equivalent of 4 spaces instead of 8.
```
autocmd FileType python setlocal expandtab shiftwidth=4 softtabstop=4 tabstop=4
```
