### ISSUE TITLE
Not automatic (Neovim)

### ISSUE THREAD

**Issue by soleera** [tpope/vim-sleuth#48]
Summary:
 - Sleuth does not run automatically when opening a new buffer in Neovim.
 - Running `:Sleuth` manually works, as does adding `autocmd BufEnter * :Sleuth` to my .vimrc

Gists:
 - [init.vim](https://gist.github.com/saih792/ea308b741ca8ff5735f4110ecac8aa85)
 - [version.log](https://gist.github.com/saih792/4b4a5ee5f8df1790fec444bb8240cabe)

**Comment by tpope** [comment]
Check `:verbose set shiftwidth?`. It's possible sleuth is running, but something else is overwriting it.

Also, note it fires on the `FileType` event, so it won't work on buffers with no `'filetype'`.

**Comment by jason0x43** [comment]
> :verbose set shiftwidth?

TIL. This is amazingly useful :)

I was experiencing the same issue, and it turned out that my editorconfig plugin was overriding sleuth (I had forgotten the editorconfig config was even there).

**Comment by vegerot** [comment]
@jason0x43 you'd probably want `editorconfig` to override `vim-sleuth`, right?

**Comment by jason0x43** [comment]
Probably? That was a few years ago; maybe it made sense at the time. 😀
