### ISSUE TITLE
Add documentation on how to add default indentation settings 

### ISSUE THREAD

**Issue by dylan-chong** [tpope/vim-sleuth#50]
It would be good if there is documentation on how to use default indentation settings combined with this plugin. For example, show an example where the default settings for ruby are set to 2 spaces, and mention that this plugin will override the setting if the current file has four spaces indenting. (By the way is that last statement correct?)

**Comment by jounathaen** [comment]
I agree. 
I really like the Plugin, but the I'd personally rather set the default tabwidth to 4. 
I looked in the code, and it looks like it is hardcoded to 8. (But I have no real idea of how vimscript works)
Taking already set parameters of tabstop and shiftwidth into account would make this plugin a must-have plugin.

**Comment by aleclarson** [comment]
@tpope Ping. 😘

I would love to know how to set the default indentation to 2 spaces when `vim-sleuth` has nothing to go off of.

**Comment by dylan-chong** [comment]
@aleclarson see my pull request (#55)
