### ISSUE TITLE
shiftwidth has a weird default value

### ISSUE THREAD

**Issue by alesandar** [tpope/vim-sleuth#51]
Executing `:verbose set shiftwidth` returns:
```
shiftwidth=7
Last set from ~/.cache/dein/.cache/init.vim/.dein/plugin/sleuth.vim
```
So that value looks very weird to me. It does not matter if sw/ts/sts has being set in my configuration file. 
I have also tested it with a very clean configuration file, including only my plugin manager and vim-sleuth.

**Comment by tpope** [comment]
The passage you cite is for `'tabstop'`, not `'shiftwidth'`. It's certainly possible to get a `'shiftwidth'` of 7 for a weirdly formatted file. Any lines in the file start with exactly 7 spaces?

**Comment by alesandar** [comment]
You're right, thanks for the fast reply and excuse me for the bad quote.
I will edit the issue description and title in a minute.

The file I've been editing was [dwm.c](https://git.suckless.org/dwm/plain/dwm.c) and I believe that the suckless community has strict rules about formatting, but whatever. It seems that the problem was caused by the enum declarations around line 64.
```c
/* enums */
enum { CurNormal, CurResize, CurMove, CurLast }; /* cursor */
enum { SchemeNorm, SchemeSel }; /* color schemes */
enum { NetSupported, NetWMName, NetWMState, NetWMCheck,
       NetWMFullscreen, NetActiveWindow, NetWMWindowType,
```
I believe that such situations are hard to be caught, but don't  you think that any odd number is a pretty weird value for indentation (the case with that file is an alternative indentation style used just at one place, in order get somehow prettier alignment).

Feel free to close the issue.

**Comment by tpope** [comment]
Ugh, yeah, that is hard to catch. Filtering out odd numbers would stop it but it could have just as easily been 6, or heck, 4 in a language with different keywords.

I'm pushing up an odd exclusion for now.

**Comment by alesandar** [comment]
It was not necessary, but it looks a little bit more convenient in this way, at least to me. Thank you.
However, it may confuse other users why they've `shiftwiwth=6`, for example.

Just an idea, not sure if you'll like it. It may slow down the processing a little bit.
Let's take into account the same file. Use the following commands and see their output.

`:0,1000s/^\ \ //n` - returns *4 matches on 4 lines*.
`:0,1000s/^\t//n` - returns *574 matches on 574 lines*.

We obviously have a lot more lines that start with single hard tab character in the beginning, rather than lines starting with two spaces (one space is not an indentation for sure, just some multi-line comment alignment of asterisks). How about implementing a similar check within your script, then deciding if you should look for soft or hard tabs?

**Comment by tpope** [comment]
That would be ideal, yes. But keep in mind the biggest count is not always the winner, as you can have a file with a shiftwidth of 2 where 99% of the lines are nested with 4+ indent, for example.
