### ISSUE TITLE
Identing with tabs when the file contains consist 4-space identation

### ISSUE THREAD

**Issue by colemickens** [tpope/vim-sleuth#56]
I open this file: https://raw.githubusercontent.com/pulumi/examples/master/kubernetes-ts-guestbook/index.ts

When I go to a random spot and hit enter, it drops me on an incorrectly idented line (tabs, not spaces).

**Comment by tpope** [comment]
Can't reproduce. Check `:verbose set expandtab?` to see if Sleuth really is the culprit.

**Comment by colemickens** [comment]
Maybe I had pasted the file in and hadn't reopened the file. I can't reproduce today, though I was sure I was yesterday. I'm assuming it's user error on my part. Sorry, thanks for taking a look.

**Comment by ideoforms** [comment]
Hi there @tpope, I have just encountered this problem too. I've done some digging and tracked it down to this:

```
let softtab = repeat(' ', 8)
...
elseif line =~# '^' . softtab
      let heuristics.soft += 1
endif
```

If I open up a short script which only has one level of indentation, e.g.:
```
#!/usr/local/bin/python
if True:
    pass
```

..no lines are present which begin with 8 spaces, and therefore no soft tab is detected, and hard-tabs are assumed (thus expandtab overridden by Sleuth). It may be that @colemickens experienced the issue when his source file was short, but then it went away as extra indentation was added.

I have tested a fix which is to decrease the above value to `4`, and it works fine for my use cases. (Of course, for files which use a 2-space soft tab, a minimum soft tab of `2` would be needed...)

Happy to create a PR containing the above if it's useful. As a many-year Sleuth user, I'm amazed that i've only just run into it!
