### ISSUE TITLE
Ignore indentation inside heredocs

### ISSUE THREAD

**Issue by xordspar0** [tpope/vim-sleuth#59]
I have a shell script file that is tab indented. It contains a heredoc that is manually aligned with spaces.

Sleuth erroneously thinks the spaces inside the heredoc are part of the indentation of my code, so it sets tabstop to 8, which is the default for files that contain mixed tabs and spaces for indentation. 

Instead, Sleuth should ignore the contents of the heredoc and recognize that my shell script is exclusively tab indented.

As mentioned in https://github.com/tpope/vim-sleuth/pull/17#issuecomment-292823139, heredocs could be added to the list of guards: https://github.com/tpope/vim-sleuth/blob/b6347df73719dea0fb14695eae4d3506ebc4a36c/plugin/sleuth.vim#L25-L61

**Comment by djeikyb** [comment]
I have a case where my shell script with a bunch of functions is indented with four spaces. I have one heredoc in a function and it appears to trick vim-sleuth into setting indentation to three spaces.

```sh
usage() {
    cat <<EOF
usage: $SELF <command> [<args>]

Commands:

restore a backup
   restore            Restore the latest dev backup
   restore env=live   Restore the latest backup for the live environment
   restore <path>     Restore a specific backup

create a backup
   backup             Back up the dev env's database

EOF
}

```

**Comment by tpope** [comment]
I'd add a "good first issue" label, but I don't have one because it's so rare that it happens!

**Comment by djeikyb** [comment]
Aw dang, far from rare for me. Majority of my vim usage is shell scripts and almost all my shell scripts have a usage function with a heredoc. Maybe this is the issue that gets me contributing back to the vim ecosystem!

**Comment by tpope** [comment]
I mean "good first issue" is rare. Most issues on most of my plugins require a lot more context.

**Comment by djeikyb** [comment]
Ohhhh! Good to hear! Added to my project list!

**Comment by sheerun** [comment]
vim-polyglot now correctly ignores heredoc when detecting indentation. also it won't allow for 3-spaces indent, just 2, 4, and 8
