### ISSUE TITLE
shiftwidth for commit messages is 22

### ISSUE THREAD

**Issue by jsatk** [tpope/vim-sleuth#60]
<img width="955" alt="Screen Shot 2019-07-09 at 10 40 43 AM" src="https://user-images.githubusercontent.com/1005550/60910604-1e316c80-a236-11e9-8b3d-e4a62dd01100.png">

This seems incorrect and strange. Any idea how to get it to stop doing this? 

FWIW I've had this plugin installed a long time. This behavior is new.

**Comment by tpope** [comment]
What's in the file?

**Comment by jsatk** [comment]
It's code for work so I can't show it here, but I pressed `cvc` from Fugitive's `:Gstatus` screen, opening up a verbose commit message window. Wondering if something in there threw it off. This doesn't happen every time, but seemingly randomly.

**Comment by tpope** [comment]
I'm not sure why you're surprised that the contents of the diff might affect the detection? You say "the behavior is new" but the plugin hasn't had any code changes in over a year so I'm not sure what you're basing that on.

Regardless, the first part of the solution is probably some sort of hard coded filetype blacklist.

**Comment by jsatk** [comment]
Thanks.  I'm not sure how the plugin works.  It's something I've just started noticing.  Probably because I'm in a new repo and the code formatting is throwing Sleuth off and making it think 22 spaces is the shiftwidth I want.

Either way, not a bug.  Thanks for following up.
