### ISSUE TITLE
File with no indents results in expandtab=0

### ISSUE THREAD

**Issue by Avi-D-coder** [tpope/vim-sleuth#61]
I believe this is inconsistent with readme?
```haskell
module Main where

import Lib

main :: IO ()
main = someFunc
```

**Comment by tpope** [comment]
Inconsistent with what in the readme, exactly?

**Comment by Avi-D-coder** [comment]
> _or, in the case the current file is new, blank, or otherwise insufficient, by looking at other files of the same type in the current and parent directories_ 

I had interpreted this file to be "otherwise insufficient".

**Comment by tpope** [comment]
Are there other files of the same type in the current or parent directories?

**Comment by Avi-D-coder** [comment]
I believe the project was in my home directory. There was not a hs file directly above, but their were certainly other Haskell projects. Does it only look directly above?

**Comment by tpope** [comment]
It looks at *files* in each parent directory. It does not recurse into sibling directories, that would take ages.
