### ISSUE TITLE
single backtick in shell comment trips heuristics

### ISSUE THREAD

**Issue by step-** [tpope/vim-sleuth#62]
A shell script of mine starts with
```sh
#!/bin/dash
# FIXME awk: fatal: can't open source file `./checksum.awk' for reading (No such file or directory)
```
and continues with a few more comments then hard-tab indented commands.

Because the FIXME line matches the pattern that detects the beginning of a backtick block, and no subsequent line matches the pattern that detects the end of a backtick block, function `guess` slurps the whole file as a very long backtick, never detecting spaces, hard tabs or even incrementing any heuristics counter.

What happens next depends on the contents of neighboring files. In my case one of them was indented with spaces, and sleuth based its guess on that file. Therefore, it ended up setting `expandtabs` on the first script --the one indented with hard tabs.

So that FIXME line trips heuristic detection. Of course I will delete that line. It's unfortunate that most *nix utilities print the "No file or directory" error message quoting the filename between a backtick and a straight tick.

The moral of this story is, don't place shell comments before an indented line (strict moral) or, if you do, ensure that no comment line includes a single backtick (soft moral).

Morals apart, I'm not sure if anything can be done to fix this issue conclusively, if heuristics could ever be conclusive, but perhaps adding a comment to the docs?

Or perhaps modifying `guess` to take a second look at the file when it's about to exit with all heuristics counters set to zero and a comment/backtick flag still on, which was exactly my case.

Thanks for this plugin. By installing this plugin, I was able to remove all indenting related configuration from my vimrc and after files. Spot on!

**Comment by tpope** [comment]
At the risk of opening Pandora's box, I'm making the backtick check specific to Go.
