### ISSUE TITLE
E930: Cannot use :redir inside execute()

### ISSUE THREAD

**Issue by cuviper** [tpope/vim-sleuth#68]
When I enable [vim-lsp](https://github.com/prabirshrestha/vim-lsp)'s `g:lsp_diagnostics_float_cursor` and move to one of the highlighted issues in my source, I get an error from vim-sleuth:

```
Error detected while processing function <SNR>130_debounceTimeTimerCallback[1]..<SNR>130_mapFSourceCallback[1]..<SNR>130_distinctUntilChangedSourceCallback[14]..<SNR>130_filterSourceCallback[6]..<SNR>130_filterSourceCallback[6]..<SNR>130_mapFSourceCallback[1]..<SNR>130_subscribeSourceCallback[2]..<lambda>8[1]..<SNR>137_show_float[3]..lsp#ui#vim#output#preview[45]..lsp#ui#vim#output#setcontent[4]..FileType Autocommands for "*"..function <SNR>68_detect[10]..<SNR>68_patterns_for:
line    5:
E930: Cannot use :redir inside execute()
```

The corresponding script numbers in that backtrace are:

```
 68: ~/.vim/bundle/sleuth/plugin/sleuth.vim
130: ~/.vim/bundle/lsp/autoload/lsp/callbag.vim
137: ~/.vim/bundle/lsp/autoload/lsp/internal/diagnostics/float.vim
```

This is on Fedora 32, VIM version 8.2.1551.

Please let me know if there's more info I should provide. Maybe this is ultimately vim-lsp's error, I'm not sure.

**Comment by tpope** [comment]
At first glance I'd say [this use of `win_execute()`](https://github.com/prabirshrestha/vim-lsp/blob/ec3090d161ea8b18f6159965f109ba192afb8188/autoload/lsp/ui/vim/output.vim#L158), which does nothing but set `&filetype`, would be much cleaner as a `setbufvar()`.

**Comment by cuviper** [comment]
Thanks! That suggestion works for me: https://github.com/prabirshrestha/vim-lsp/pull/911
