### ISSUE TITLE
New release (last one is 7 years old)

### ISSUE THREAD

**Issue by heinrich5991** [tpope/vim-sleuth#69]
Hey, thanks for your script, I've been using it for a long time. I've almost never had to think about indentation again.

Since I wanted to install it globally for all users, I'm creating an Archlinux package for it. Would it be possible to do a new release? The last one (1.1) is seven years old and there have been plenty of commits since then.

**Comment by tpope** [comment]
8 years now, I guess it's time.

**Comment by heinrich5991** [comment]
Thanks! Updated the PKGBUILD: https://aur.archlinux.org/packages/vim-sleuth/.
