### ISSUE TITLE
Markdown files takes >= 20 seconds to load

### ISSUE THREAD

**Issue by Istanful** [tpope/vim-sleuth#70]
For me markdown files takes a good 20 seconds to load. This seems to be derived from the fact that sleuth traverses the tree to find indentation in other files when it cannot immediately infer it from the opened file.

I suspect that since markdown files seldom uses indentation, sleuth will never find a match and block the file from loading until it has traversed the entire tree.

I don't know what would be a good solution for this. Maybe a timeout?

I don't know the specifics about markdown. If they all have the same indentation characters maybe you could even blacklist md files?

I changed to the Detectindent plugin and have not had problems since.

**Comment by roachsinai** [comment]
Maybe a project root marker?

**Comment by Istanful** [comment]
@roachsinai You mean for it to stop traversing the tree when the working directory is found?

That would be a simple but effective fix I think.

**Comment by smichel17** [comment]
As a workaround, you can disable auto-detection by setting `sleuth_automatic=0` (toggle is both global and per-buffer):

https://github.com/tpope/vim-sleuth/blob/38bd4010110614822cde523ebc5724963312ab63/plugin/sleuth.vim#L196-L202

You should be able to do that for markdown files with something like:

```vim
autocmd FileType markdown :setlocal sleuth_automatic=0
```

However, my vim-script-fu is not *particularly* strong; I'm not sure how to guarantee that this autocmd runs before vim-sleuth's.

**Comment by tpope** [comment]
Markdown performance has come up before. It's compounded because there are so many dang file extensions for it, but even still, I'm impressed you managed to hit 20 seconds.

 Neighbor detection isn't that useful for Markdown so I'm going to try disabling it entirely.
