### ISSUE TITLE
Sleuth not working when a modeline is setting the filetype

### ISSUE THREAD

**Issue by mildred** [tpope/vim-sleuth#71]
Given the following file:

```
<script>
  // vim: ft=html

  // script indent
    // indent two spaces
      // up to some level

</script>
```

I open the file in Vim, I run `:Sleuth`. It should set my indentation to two spaces.

When I indent a line once more than in the example, i get a tab character, mixing spaces and tabs. Something I'd like to avoid. Indentation settings is detected as `ts=8 sts=-1 sw=2 et=0 ai=1`

Removing the modeline makes it work (indentation setting is detected as `ts=8 sts=-1 sw=2 et=1 ai=1`).

**Comment by mildred** [comment]
Workaround is to ensure `expandtab` is set:

```vim
autocmd BufEnter * :Sleuth | :set expandtab
```

**Comment by tpope** [comment]
I can't reproduce. Is the file detected as HTML without the modeline?

**Comment by wobo-evan** [comment]
I'm getting a similar issue with TypeScript. I open a new, blank test.ts file and run `:Sleuth,` then type - no indenting happens. running `:verbose set shiftwidth?` gives` shiftwidth=8`. If I type, THEN run `:Sleuth`, it formats properly. For some reason, blank TypeScript files don't properly call :Sleuth on start (it seems). Any thoughts, @tpope?

**Comment by tpope** [comment]
If the file is empty, and it can't find any other files to detect from, then `shiftwidth=8` is the expected fallback behavior.

**Comment by tpope** [comment]
`:verbose Sleuth` will now report the reason each option is set.
