### ISSUE TITLE
`indentexpr` mysteriously set

### ISSUE THREAD

**Issue by jakobcornell** [tpope/vim-sleuth#72]
Hello!  I recently started using this plugin and I've found it quite convenient, but it seems it's configured a bit too much for my taste.  I have `autoindent` set in my vimrc so that when I press Enter in insert mode I start the new line at the same indentation level as the current line.  This seems to have changed since adding vim-sleuth, as now indentation is automatically added in a few places it wasn't before.  The automatic indentation doesn't agree with my code style, so I'd rather not have vim try to indent any more intelligently than `autoindent`.

I think what's causing this behavior is `indentexpr` being set, but looking at the plugin source I don't think vim-sleuth is doing it directly.  Can someone explain how this is getting set and how I can restore the original indentation behavior?  I wonder if this may also be considered a bug, since the readme for this project seems to only indicate that the plugin affects `shiftwidth`, `expandtab`, `softtabstop`, and `smarttab`, and doesn't document that autoindent behavior is affected.

**Comment by tpope** [comment]
It does call `filetype indent on` if it wasn't called already. Is that what's throwing you off?

**Comment by jakobcornell** [comment]
Ah yes, looks like that's what was causing it.  Is that independent of the tab/space detection?  If so I would think it could be removed and users could opt in by including it in their vimrc.  Or alternatively, is there a way to prevent vim-sleuth from invoking that other than changing the plugin source?

**Comment by tpope** [comment]
I would encourage you to look into disabling `'indentexpr'` for the file type that is giving you trouble (probably by adding `setlocal indentexpr=` to `.vim/after/indent/whatever.vim`). If you do insist on opting out of the 21st century entirely, adding `let g:did_filetype_on = 0` to your vimrc would probably do the trick.

**Comment by jakobcornell** [comment]
The counterproductive indentation is happening pretty much across the board, so I went with your nuclear option.  Looks like you meant `g:did_indent_on`, which works like a charm.  Thanks for the quick responses.
