### ISSUE TITLE
textwidth shouldn't be affected for gitcommit filetype

### ISSUE THREAD

**Issue by nikitabobko** [tpope/vim-sleuth#79]
Steps to reproduce:
1. create `.editorconfig` with such content:
```
[*]
max_line_length = 140
```
2. `git commit`
Expected: `textwidth` is 72 (it's default value)
Actual: `textwidth` is 140

**Comment by nikitabobko** [comment]
It's not expected because in a lot of projects people set `max_line_length` as a default value for all files in the project. And just happens that `.git/COMMIT_EDITMSG` is located inside the project directory. `.editorconfig` isn't supposed to configure commit formatting options.

I'm not sure whether `vim-sleuth` should or shouldn't apply other `.editorconfig` formatting options for gitcommit file type (such as `expandtab`/`shiftwidth`). On one hand, people put code snippets into commit messages so it would be good if snippets followed project code style, on the other hand `.editorconfig` isn't supposed to set formatting options for commit messages so I'm afraid of other corner cases.

**Comment by tpope** [comment]
> It's not expected
It's very much expected, at least by some people. 
 Here's a project that explicitly relies on it: <https://github.com/git/git/blob/38062e73e009f27ea192d50481fcb5e7b0e9d6eb/.editorconfig#L15-L16>. Perhaps you've heard of it.

> `.editorconfig` isn't supposed to configure commit formatting options.

According to who, exactly?

**Comment by tpope** [comment]
Note that this particular problem has a straightforward workaround:

```sh
printf '[COMMIT_EDITMSG]\nmax_line_length = 72\n' > .git/.editorconfig
```
