### ISSUE TITLE
[Bug] Argument mismatch at s:ModelineOptions

### ISSUE THREAD

**Issue by CoelacanthusHex** [tpope/vim-sleuth#81]
In https://github.com/tpope/vim-sleuth/commit/39bf888177c5b0936b15c44344bb8d5a2de04262, arguments of s:ModelineOptions change from 1 to 0, but https://github.com/tpope/vim-sleuth/blob/39bf888177c5b0936b15c44344bb8d5a2de04262/plugin/sleuth.vim#L441 still use it with one argument.
It leads to an error when loaded,
```
E118: Too many arguments for function: s:ModelineOptions
E116: Invalid arguments for function extend
```
I think just removing arguments when called can fix it, but I'm not sure whether there is a side effect.

**Comment by tpope** [comment]
Gah, forgot to stage a hunk. Thanks for the heads up.
