### ISSUE TITLE
Golang files tabstop is 8

### ISSUE THREAD

**Issue by timsofteng** [tpope/vim-sleuth#82]
I believe I've faced up with same issue
https://github.com/tpope/vim-sleuth/issues/74

Wrong indent for `go` files.
`sleuth` detect it as 8 but I guess it shoud be 4.

`:verbose Sleuth` in go file

```
:setlocal noexpandtab           " from %
:setlocal shiftwidth=0          " from %
```

In python file it looks correct:
```
:setlocal expandtab             " from %
:setlocal shiftwidth=4          " from %
```

```
> nvim -v
NVIM v0.7.0
```

**Comment by timsofteng** [comment]
@tpope thanks. You are right
Here is whole `/usr/share/nvim/runtim/frplugin/go.vim` file

```
" Vim filetype plugin file
" Language:	Go
" Maintainer:	David Barnett (https://github.com/google/vim-ft-go)
" Last Change:	2014 Aug 16

if exists('b:did_ftplugin')
  finish
endif
let b:did_ftplugin = 1

setlocal formatoptions-=t

setlocal comments=s1:/*,mb:*,ex:*/,://
setlocal commentstring=//\ %s

let b:undo_ftplugin = 'setl fo< com< cms<'

" vim: sw=2 sts=2 et
```

Nothing about tabstop. Should I open issue in neovim repo?

**Comment by tpope** [comment]
No, I'm telling you to create your own file—`~/.config/nvim/after/ftplugin/go.vim`—which will run afterwards. The fact you want `tabstop=4` or whatever is your personal preference.

**Comment by timsofteng** [comment]
Got it. Thanks Tim.

**Comment by timsofteng** [comment]
@tpope sorry for disturbing but I have another one small question.
So I haven't any `.vim` file for `javascript` filetype.
And indent works perfectly in .js files inside my project
`:verb setl sts? sw? et?`
```
  softtabstop=-1
        Last set from ~/.local/share/nvim/site/pack/packer/start/vim-sleuth/plugin/sleuth.vim line 642
  shiftwidth=2
        Last set from ~/.local/share/nvim/site/pack/packer/start/vim-sleuth/plugin/sleuth.vim line 642
  expandtab
        Last set from ~/.local/share/nvim/site/pack/packer/start/vim-sleuth/plugin/sleuth.vim line 642
```

But on separate js files it works completely differently (same command)
```
  softtabstop=0
  shiftwidth=8
noexpandtab
```

Why is it happens? Why is `sleuth` behavior different?

**Comment by tpope** [comment]
Sleuth looks at the file and tries to guess the correct indent. Different file, different results. `:verbose Sleuth` can sometimes offer clues as to why.

If you have a file it gets wrong, you can always use EditorConfig or modelines to override it.

**Comment by timsofteng** [comment]
> Sleuth looks at the file and tries to guess the correct indent. Different file, different results. `:verbose Sleuth` can sometimes offer clues as to why.
> 
> If you have a file it gets wrong, you can always use EditorConfig or modelines to override it.

Oh. Sleuth looks into another file in my project. Is it normal behavior?

**Comment by tpope** [comment]
Yes, it consults other files if it can't figure it out. This is in the README. (Looks like I need to add it to the to the help file.)

**Comment by timsofteng** [comment]
> Yes, it consults other files if it can't figure it out. This is in the README. (Looks like I need to add it to the to the help file.)

I didn't dive into docs enough. Thank you for your help.
