### ISSUE TITLE
Set new file default tabstop?

### ISSUE THREAD

**Issue by tomstark99** [tpope/vim-sleuth#85]
I would like to set the default tabstop to be 4 for all unrecognised file types and also file types that do not require specific sizes (e.g. like yaml).

I have changed
`let tabstop = get(a:detected.options, 'tabstop', get(a:detected.defaults, 'tabstop', [8]))[0]`
to
`let tabstop = get(a:detected.options, 'tabstop', get(a:detected.defaults, 'tabstop', [4]))[0]`

however that doesn't seem to have made a difference, is there any way to achieve what I am asking?

**Comment by tpope** [comment]
Sleuth's default is always to do nothing, that is, defer to the Vim default. If you want to change the default `'tabstop'`, set it in your vimrc like any other option.

> (e.g. like yaml)

Curious example as Yaml explicitly forbids hard tabs. Sounds like you might want to set `'shiftwidth'` instead.
