### ISSUE TITLE
echo execute() gives "Sleuth failed to detect indent settings"

### ISSUE THREAD

**Issue by samhed** [tpope/vim-sleuth#86]
Sleuth writes an error message when I run an `echo execute` command that results in a new buffer being opened. For example `:echo execute("e newfile")`. The error I get is:

> Sleuth failed to detect indent settings

The reason I want `echo` in front of execute sometimes is that I don't want to miss any errors. If I omit `echo` I only see the latest error. The actual use case I have for this is a function that can run any vim-fugitive command. These open git blames, logs and diffs in new buffers.

The workaround I use currently is to omit `echo`, this way I don't get the sleuth error.

Can reproduce with only this in .vimrc:

```
call plug#begin()
  Plug 'tpope/vim-sleuth'
call plug#end()
```

**Comment by tpope** [comment]
Now that I think about it, you don't want `:call execute('e newfile')`, you want `:execute 'e newfile'`. Redirecting output to a string only to echo it back out is just adding an unnecessary leaky abstraction to the whole process.

**Comment by samhed** [comment]
Thanks for helping, `:execute 'e newfile'` seems to work
