### ISSUE TITLE
eol/endofline is not inferred correctly (empty line at end of file always gets removed after editing)

### ISSUE THREAD

**Issue by dylan-chong** [tpope/vim-sleuth#87]
1. Run
```vim
echo bla >> testfile
echo bla >> testfile
echo bla >> testfile
echo >> testfile
nvim -u NONE --cmd 'so /Users/Dylan/.vim/plugged/vim-sleuth/plugin/sleuth.vim' testfile
```
2. you should clearly see a blank line after the last `bla` in the file.
3. add some character to the first line of the file
4. save
5. reopen the file with `nvim -u NONE testfile`
6. you'll see no empty new line at the end of the file

To show this is indeed caused by sleuth, run the steps again but without sourcing sleuth

Have had this issue for a while where the new lines at the end of files disappears

For some reason `set eol?` always returns `noendofline`

Even adding `--cmd 'set eol'` after `NONE` does not change the outcome

**Comment by tpope** [comment]
I can't reproduce. Maybe you have an `.editorconfig` with `insert_final_newline = false` in a parent directory?

**Comment by dylan-chong** [comment]
Cheers for the quick reply! Looks like .editorconfig is the case!
