### ISSUE TITLE
Tabstop is 8 for LaTeX file

### ISSUE THREAD

**Issue by 3nt3** [tpope/vim-sleuth#89]
Sorry, I'm new to this plugin but if I don't override it in my `.editorconfig`, the tabstop seems to default 8 which is pretty unreadable.

**Comment by tpope** [comment]
Normally you can just `set tabstop=8` in your vimrc and Sleuth will respect it. The only time it forces 8 is when you have a file that mixes spaces and tabs, for consistency. If this is happening to you, then you can fix the file to only use tabs, or use `.editorconfig` or a modeline to force it.

There's also an experimental option that may or may not help:

```vim
let g:sleuth_tex_defaults = 'tabstop=4'
```

**Comment by Fau818** [comment]
> 

I like this experimental option.
In my view, it would be nice if there was an option to customize the default value of `tabstop`.

But this experimental option doesn't work for me yet. So, when will this option become available?

**Comment by tpope** [comment]
It works now. The _default_ is customizable. It's not an absolute override if Sleuth detects something else. Try with an empty file.

Check `:verbose Sleuth` to see more information about why particular options are set.

**Comment by 3nt3** [comment]
```vim
:setlocal noexpandtab           " from %                                                                               
:setlocal shiftwidth=0          " from %                                                           
:setlocal tabstop=8             " from %
```

when I don't set `g:sleuth_tex_defaults`, it just displays this.
