### ISSUE TITLE
Failed to detect indent setting on .hpp files

### ISSUE THREAD

**Issue by ciuckc** [tpope/vim-sleuth#90]
Hi, I recently started using this plugin with cpp. For .cpp, :Sleuth gives me: `:setlocal et sw=2` , but on .hpp files, it says `:Sleuth failed to detect indent settings`.
Any idea what might be the issue here? Thank you very much.

**Comment by tpope** [comment]
That generally only happens for files that aren't indented. For a header file, this makes sense. It'll check other files in the directory, but they may have the same problem, and it stops after 8 files.

There's an undocumented option you may like:

```
let g:sleuth_cpp_globs = ['*.cpp', '*.hpp']
```

This will make all cpp files look for both those globs. By default it only looks for files with the same extension.
