### ISSUE TITLE
Indent settings not detected on files without a filetype

### ISSUE THREAD

**Issue by bshimanuki** [tpope/vim-sleuth#94]
vim-sleuth fails to detect indent settings in a file that does not have a filetype (eg, a file with a custom extension).

**Expected Behavior**: Detect indent settings based on the current file. Either skip siblings/parent directories or look at other files with the same extension (if it has an extension).

**Actual Behavior**:  The `DetectHeuristics` short circuits on https://github.com/tpope/vim-sleuth/blob/1cc4557420f215d02c4d2645a748a816c220e99b/plugin/sleuth.vim#L520 due to the empty filetype check

**Comment by tpope** [comment]
I think this is wontfix. The code in question runs before the filetype is set. That means heuristics would get triggered even for [disabled filetypes](https://github.com/tpope/vim-sleuth/blob/1cc4557420f215d02c4d2645a748a816c220e99b/doc/sleuth.txt#L57-L61). Furthermore, heuristics are in turn partially based on the file type, which means they'll be even dumber than usual if no file type is set.

It is very easy to add a custom filetype for a custom file extension, if one wants one:

```vim
autocmd BufNewFile,BufReadPost *.myextension setf myfiletype
```
