### ISSUE TITLE
Ignore terminal buftype for vim-sleuth.

### ISSUE THREAD

**Issue by 231tr0n** [tpope/vim-sleuth#99]
Hi tpope! Thank you for developing this amazing plugin. Is it possible to ignore buftype terminal. This plugin is actually triggering for terminal buftypes when I use fzf-lua.

**Comment by tpope** [comment]
It's already ignored: https://github.com/tpope/vim-sleuth/blob/be69bff86754b1aa5adcbb527d7fcd1635a84080/plugin/sleuth.vim#L598-L600

What specific symptoms are you actually experiencing?

**Comment by 231tr0n** [comment]
> It's already ignored:
> 
> https://github.com/tpope/vim-sleuth/blob/be69bff86754b1aa5adcbb527d7fcd1635a84080/plugin/sleuth.vim#L598-L600
> 
> What specific symptoms are you actually experiencing?

NVM, it seems to be a issue with my configuration. Really sorry for raising this issue. I am calling :Sleuth command which is getting called for any buffer with filetype event and i am supposed to ignore buftypes which are not required manually. That was my mistake.

**Comment by 231tr0n** [comment]
@tpope one last doubt, like in the docs, it says g:sleuth_automatic is deprecated but when i look into the code it still seems to be used to set auto commands. Is this global variable not to be used anymore?

**Comment by tpope** [comment]
I don't recommend it.

**Comment by phanen** [comment]
It seems vim-sleuth indeed enabled on nvim's terminal buffer. `buftype` check fail since nvim haven't set buftype=terminal at that time.

workaround
```vim
        function! ExcludeBufferFromDiscovery(file, plugin) abort
          return a:plugin ==# 'sleuth' && a:file =~# '^term://'
        endfunction
```
